pipeline:
  identifier: Build_gosample_1686774275734
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: Test_1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1686690011100
        repoName: rosspotter/gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
